
[build]
  functions = "functions"
  publish = "public/"

#[[redirects]]
#  from = "/discord"
#  to = "https://discord.gg/A4BGVFKwJv"

# [dev]
#   framework = "#custom"
#   command = "read" # Command to start your dev server
#   port = 8888 # The port that the netlify dev will be accessible on
#   targetPort = 3000

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200