#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

# WEB SHIT
cd web

npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)
